### ISSUE TITLE
Product description

### ISSUE THREAD

**Issue by Sandipgit2999** [parthdeshmukh2/affable-scissors-7552#5]

**Comment by parthdeshmukh2** [comment]
useEffect(()=>{
if(watches.length ===0){
dispatch(getData());
}
},[watches.length, dispatch]);
useEffect(()=>{
if(id){
const currentWatch = watches.find((elem)=> elem.id === Number(id));
currentWatch && setCurrtWatch(currentWatch);
}
}, [id, watches])
