### ISSUE TITLE
Construct week Project Review

### ISSUE THREAD

**Issue by rahulkore** [parthdeshmukh2/affable-scissors-7552#88]
# Review Comments
- UI Aspects
  - Pros
    - UI looks good , looks attractive , good job on that part . 
    - The wireframe looks great overall.
    - The navigation is smooth on the site.
    - latency is within limits on event fires.
    - Functionality those are included works fine although some enhancements could've done .
    - Redux arch is used properly , kudos on that . 
    - Hooks understanding is also on point . 
    - Standard Coding practices are used .
    
  - Cons
     - When hovering over images , it gives a clickable pointer , Although they aren't .
     - Client side data validation is missing.  
     - Some links are broken . 
     - Responsiveness is handled , Although on some place it gets broken if abused , like on the product detail page the heart icon which is aligned on the `add to bag`  is not responsive.
     - Not much comments are present .
     - loading indicators are missing .
  

- Backend Aspects
  - Not much is done considering back end 
  - The Api call that happens for use creation and login both just creates and adds an user , not much apart from that .
  - A database could have been created , and sessions for each user could've been maintained .
  - Like when i do a create user , user is getting created and login happens but the page does not have my name on it .
  - Add to cart is general and not user specific .
  - Add cart got broken when i added some elements in it for some of the elements . and price was being shown as $NAN
  

-Overall Comments 
  - Little more focus on back end could have been great .
  - some of the components from UI could have been reduced and that much effort could have been given to back end side development .
  - overall It's a good project , a lot of promise is shown .
  - coding standard , functionality all are maintained at a good quality .
  - Most of the work was done by the team lead . that should not be the case .
  - use of git is done very good , design patterns are good .

**Comment by parthdeshmukh2** [comment]
Sir, we tried our best but due to time constraints, we were unable to make it as per our expectations. But we ensure that we will work on the suggestion you mentioned above. We will make sure that we will work on the backend more. And we will try to make the Cart page responsive as well as user-specific.
 Thank you, Sir,  for your valuable review
